package pl.edu.agh.semsimmon.common.api.resource;

/**
 * Interface for listeners of events generated by {@link pl.edu.agh.semsimmon.common.api.transport.TransportProxy}
 *
 * @author koperek
 */
public interface IResourceDiscoveryListener {

  /**
   * @param event
   */
  public void processEvent(IResourceDiscoveryEvent event);
}
